<!-- include(datastructures.apib) -->

# Group Scripts

## Scripts [/scripts]

### Create [POST]

+ Request (application/vnd.api+json)

    + Attributes (ScriptsPOST)

<!-- include(../../common/json-api.schema) -->

+ Response 201 (application/vnd.api+json)

    + Attributes (ScriptGET)

<!-- include(../../common/json-api.schema) -->

### List [GET]

+ Response 200 (application/vnd.api+json)

    + Attributes (ScriptsGET)

<!-- include(../../common/json-api.schema) -->

## Script [/scripts/{id}]

+ Parameters
    + id: 5c210cb2de633285fe5e3e34 (required, string) - ID of the object

### Get info [GET]

+ Response 200 (application/vnd.api+json)

    + Attributes (ScriptGET)

<!-- include(../../common/json-api.schema) -->

### Change [PATCH]
Updates content of the script and updates timestamp.

+ Request (application/vnd.api+json)

    + Attributes (ScriptPATCH)

<!-- include(../../common/json-api.schema) -->

+ Response 200 (application/vnd.api+json)

    + Attributes (ScriptGET)

<!-- include(../../common/json-api.schema) -->

### Delete [DELETE]

+ Response 204
