<!-- include(datastructures.apib) -->

# Group Boot Files

## Boot Files [/boot_files]

### Register file [POST]

+ Request (application/vnd.api+json)

    + Attributes (BootFilesPOST)

<!-- include(../../common/json-api.schema) -->

+ Response 201 (application/vnd.api+json)

    + Attributes (BootFileGET)

<!-- include(../../common/json-api.schema) -->

### List [GET]

+ Response 200 (application/vnd.api+json)

    + Attributes (BootFilesGET)

<!-- include(../../common/json-api.schema) -->

## Boot File [/boot_files/{id}]

+ Parameters
    + id: 5c2165c76c51cc414795a579 (required, string) - ID of the object

### Get info [GET]

+ Response 200 (application/vnd.api+json)

    + Attributes (BootFileGET)

<!-- include(../../common/json-api.schema) -->

### Delete [DELETE]

+ Response 204
