# Data Structures

## OSImageChrootOptionsPOST
+ data (object, required, nullable)
    + type: osimage_chroot_options (string, required) - type of the resource
    + attributes (object, required)
        + path: /opt/luna/os/compute (string, required) - source of the image
        + grab_options: `-avxz -hax` (string, required) - rsync options for grabbing node
        + grab_exclude: /scripts/5c23f1bef9198396fb93420a (string, required) - uri of the exclude list for grabbing
        + grab_filesystems: /,/boot (string, required) - filesystem to grab

## OSImageChrootOptionsIdentifier
+ type: osimage_chroot_options (string, required) - Type of the resource
+ id: 5c23ee55ea17bde203abef50 (string, required) - ID of the resource
+ links (object, required)
    + self: /scripts/5c23ee55ea17bde203abef50 (string, required) - URI of the resource

## OSImageChrootOptionsGET
+ links (object, required)
    + self: /osimage_chroot_options (string, required) - URI of the resource
+ data (array[OSImageChrootOptionsIdentifier], required)

## OSImageChrootOptionGET
+ links (object, required)
    + self: /osimage_chroot_options/5c23ee55ea17bde203abef50 (string, required) - URI of the resource
+ data (object, required, nullable)
    + type: osimage_chroot_options (string, required) - type of the resource
    + id: 5c23ee55ea17bde203abef50 (string, required) - ID of the resource
    + attributes (object, required)
        + path: /opt/luna/os/compute (string, required) - source of the image
        + grab_options: `-avxz -hax` (string, required) - rsync options for grabbing node
        + grab_exclude: /scripts/5c23f1bef9198396fb93420a (string, required) - uri of the exclude list for grabbing
        + grab_filesystems: /,/boot (string, required) - filesystem to grab
+ meta (object, required)
    + `last_update`: `2018-11-30 15:10:49.542714515+01:00` (string, required) - Time of the last status update (RFC 3339 format)

## OSImageChrootOptionPATCH
+ data (object, required, nullable)
    + type: osimage_chroot_options (string, required) - type of the resource
    + id: 5c23ee55ea17bde203abef50 (string, required) - ID of the resource
    + attributes (object, required)
        + path: /opt/luna/os/compute (string, optional) - source of the image
        + grab_options: `-avxz -hax` (string, optional) - rsync options for grabbing node
        + grab_exclude: /scripts/5c23f1bef9198396fb93420a (string, optional) - uri of the exclude list for grabbing
        + grab_filesystems: /,/boot (string, optional) - filesystem to grab
