FORMAT: 1A
HOST: http://localhost:7051

# Luna
RESTful api to iteract with Luna daemon

Authentication is being performed using token:

```http
Authorization: Token some_secret
```

<!-- include(common/structures.apib) -->

<!-- include(entrypoints/tasks.apib) -->

<!-- include(entrypoints/scripts.apib) -->

<!-- include(entrypoints/boot_files.apib) -->

<!-- include(entrypoints/torrent_files.apib) -->

