# Data Structures

## GroupsPOST
+ data (object, required, nullable)
    + type: groups (string, required) - type of the resource
    + attributes (object, required)
        + name: compute (string, required) - Name of the OSImage
        + domain: cluster (string, optional) - DNS domain for node
        + comment: group for compute nodes (string, optional) - Additional info about group
        + tags: rack01, chassis01 (array[string], optional) - Tags for group
    + relationships (object, required)
        + osimage (object, required)
            + data (object, required)
                + type: osimages (string, required)
                + id: 5c2580205c864055bba85b18 (string, required)
        + bmcsetup (object, required)
            + data (object, required)
                + type: bmcsetup (string, required)
                + id: 5c258030745cc66a26e14613 (string, required)
        + `kernel_options` (object, required)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c25803a0541add5c981d19c (string, required)
        + prescript (object, required)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c258043450d925189f88a0c (string, required)
        + partscript (object, required)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c25804caa21279d504ffa51 (string, required)
        + postscript (object, required)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c25805556288ffda6c8f4d8 (string, required)

## GroupElem
+ type: groups (string, required) - Type of the resource
+ id: 5c2582db72d035f0ff20dc6e (string, required) - ID of the resource
+ links (object, required)
    + self: /groups/5c2582db72d035f0ff20dc6e (string, required) - URI of the resource

## GroupsGET
+ links (object, required)
    + self: /groups (string, required) - URI of the resource
+ data (array[GroupElem], required, nullable)

## GroupInterfacesdata
+ type: interfaces (string, required)
+ id: 5c2624d16159ca7f8a73c26d (string, required)

## GroupGETdata
+ type: groups (string, required) - type of the resource
+ id: 5c2582db72d035f0ff20dc6e (string, required) - ID of the resource
+ attributes (object, required)
    + name: compute (string, required) - Name of the OSImage
    + domain: cluster (string, required) - DNS domain for node
    + comment: group for compute nodes (string, required) - Additional info about group
    + tags: rack01, chassis01 (array[string], required) - Tags for group
+ relationships (object, required)
    + osimage (object, required)
        + links (object, required)
            + self: /groups/5c2582db72d035f0ff20dc6e/relationships/osimage (string, required)
            + related: /groups/5c2582db72d035f0ff20dc6e/osimage (string, required)
        + data (object, required)
            + type: osimages (string, required)
            + id: 5c2580205c864055bba85b18 (string, required)
    + bmcsetup (object, required)
        + links (object, required)
            + self: /groups/5c2582db72d035f0ff20dc6e/relationships/bmcsetup (string, required)
            + related: /groups/5c2582db72d035f0ff20dc6e/bmcsetup (string, required)
        + data (object, required)
            + type: bmcsetup (string, required)
            + id: 5c258030745cc66a26e14613 (string, required)
    + `kernel_options` (object, required)
        + links (object, required)
            + self: `/groups/5c2582db72d035f0ff20dc6e/relationships/kernel_options` (string, required)
            + related: `/groups/5c2582db72d035f0ff20dc6e/kernel_options` (string, required)
        + data (object, required)
            + type: scripts (string, required)
            + id: 5c25803a0541add5c981d19c (string, required)
    + prescript (object, required)
        + links (object, required)
            + self: /groups/5c2582db72d035f0ff20dc6e/relationships/prescript (string, required)
            + related: /groups/5c2582db72d035f0ff20dc6e/prescript (string, required)
        + data (object, required)
            + type: scripts (string, required)
            + id: 5c258043450d925189f88a0c (string, required)
    + partscript (object, required)
        + links (object, required)
            + self: /groups/5c2582db72d035f0ff20dc6e/relationships/partscript (string, required)
            + related: /groups/5c2582db72d035f0ff20dc6e/partscript (string, required)
        + data (object, required)
            + type: scripts (string, required)
            + id: 5c25804caa21279d504ffa51 (string, required)
    + postscript (object, required)
        + links (object, required)
            + self: /groups/5c2582db72d035f0ff20dc6e/relationships/postscript (string, required)
            + related: /groups/5c2582db72d035f0ff20dc6e/postscript (string, required)
        + data (object, required)
            + type: scripts (string, required)
            + id: 5c25805556288ffda6c8f4d8 (string, required)
    + interfaces (object, required) - Interfaces for the group
        + links (object, required)
            + self: /groups/5c2582db72d035f0ff20dc6e/relationships/interfaces (string, required)
            + related: /groups/5c2582db72d035f0ff20dc6e/interfaces (string, required)
        + data (array[GroupInterfacesdata], required)

## GroupGET
+ links (object, required)
    + self: /groups/5c2582db72d035f0ff20dc6e (string, required) - URI of the resource
+ data (GroupGETdata, required)
+ meta (object, required)
    + `last_update`: `2018-11-30 15:10:49.542714515+01:00` (string, required) - Time of the last status update (RFC 3339 format)

# GroupPATCH
+ data (object, required, nullable)
    + type: groups (string, required) - type of the resource
    + id: 5c2582db72d035f0ff20dc6e (string, required) - ID of the resource
    + attributes (object, optional)
        + name: compute (string, required) - Name of the OSImage
        + domain: cluster (string, optional) - DNS domain for node
        + comment: group for compute nodes (string, optional) - Additional info about group
        + tags: rack01, chassis01 (array[string], optional) - Tags for group
    + relationships (object, optional)
        + osimage (object, optional)
            + data (object, required)
                + type: osimages (string, required)
                + id: 5c2580205c864055bba85b18 (string, required)
        + bmcsetup (object, optional)
            + data (object, required)
                + type: bmcsetup (string, required)
                + id: 5c258030745cc66a26e14613 (string, required)
        + `kernel_options` (object, optional)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c25803a0541add5c981d19c (string, required)
        + prescript (object, optional)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c258043450d925189f88a0c (string, required)
        + partscript (object, optional)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c25804caa21279d504ffa51 (string, required)
        + postscript (object, optional)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c25805556288ffda6c8f4d8 (string, required)
        + postscript (object, optional)
            + data (object, required)
                + type: scripts (string, required)
                + id: 5c25805556288ffda6c8f4d8 (string, required)

## GroupRelationshipsOSImageGET
+ links (object, required)
    + self: /groups/5c2582db72d035f0ff20dc6e/relationships/osimage (string, required) - URI of the resource
+ data (object, required)
    + type: osimages (string, required) - type of the resource
    + id: 5c2580205c864055bba85b18 (string, required) - id of the resource

## GroupRelationshipsOSImagePATCH
+ data (object, required)
    + type: osimages (string, required) - type of the resource
    + id: 5c2643247279bcdb0d2151a0 (string, required) - id of the resource

## GroupOSImageGET
+ links (object, required)
    + self: /groups/5c2582db72d035f0ff20dc6e/osimage (string, required)
+ data (OSImageGETdata, required)


