# Group Uploads

## Boot files [/uploads/bootfiles]

### Upload boot file [POST]

+ Request (multipart/form-data)

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /tasks/5c21216cc6d9ff6eab1b4365

## OSImage tarballs  [/uploads/tarballs]

### Upload osimage tarball [POST]

+ Request (multipart/form-data)

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /tasks/5c212178e68e61d84a34e147
